dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
addons:
  ssh_known_hosts:
    - liquality.io
env:
  - APP_CONFIG=./.travis/liquality.io.swap.config.js DESTINATION_PATH=/var/www/html/it/leep/swap/
  - APP_CONFIG=./.travis/liquality.io.swap-challenge.config.js DESTINATION_PATH=/var/www/html/it/leep/swap-challenge/
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_a1bc936c4a1a_key -iv $encrypted_a1bc936c4a1a_iv -in ./.travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - sudo apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev-dev
  - cp $APP_CONFIG ./src/config/config.js
script:
  - CI=false npm run build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    target-branch: gh-pages
    local-dir: "./build"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ $LIQUALITY_USER@$LIQUALITY_HOST:$DESTINATION_PATH
    on:
      branch: master
